### ISSUE TITLE
Running my python files on server, problem with path 

### ISSUE THREAD

**Issue by benfig1127** [benfig1127/Summer-Research-2020#11]
@mikeizbicki I got my code to work great on my machine with the addition of folders as inputs and looping through all the files generating the encodings, I also was able to get the tensor concatenation to work while handling all the possible edge cases. When I tried to copy the python file over and run it on the serer the following occurred: 
Here is the command, error message and output:

```
python3 UN_encoder.py --data=/home/ben/Summer_Work/home/bfigueroa20/en-es_test/ --print_tensor --batch_size=3


2020-06-04 16:27:07.375195: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
device= cuda
Traceback (most recent call last):
  File "UN_encoder.py", line 142, in <module>
    data_parser()
  File "UN_encoder.py", line 116, in data_parser
    for file in os.listdir(args.data):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ben/Summer_Work/home/bfigueroa20/en-es_test'
```
Here is the portion of the code that handles the file paths:
```
def data_parser():
	for file in os.listdir(args.data):
		print(file)
		with open(args.data+'/'+file,'r') as f_in:
```
I made sure to click on the folder I am trying to reference and copy the path exactly as shown in the properties, I am not sure what else is wrong. The confusing part is that it works perfectly fine on my machine.

**Comment by benfig1127** [comment]
@mikeizbicki never mind, I just figured it out. I was trying to route the path through my local computer and not the server. Sorry haha

**Comment by benfig1127** [comment]
@mikeizbicki Last server question sorry, I am trying to run the encoder right now with a batch size of 5 and a text file length of 1000 and it gives the following error:
```
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 10.76 GiB total capacity; 9.44 GiB already allocated; 3.12 MiB free; 10.06 GiB reserved in total by PyTorch)
```
Do I need to just wait for a while and come back? thanks

**Comment by mikeizbicki** [comment]
The GPU has only 11 GB of memory.  That's plenty for loading the model and the batch, but it's not enough to also keep all the outputs that you've calculated so far.

After you calculate the output embeddings, you should send the tensor back to the cpu so that it frees up the space on the gpu.

What you have is called a memory leak, and there are possibly other memory leaks as well, but that at least is likely one of them.
