### ISSUE TITLE
Meeting today

### ISSUE THREAD

**Issue by benfig1127** [benfig1127/Summer-Research-2020#12]
@mikeizbicki Hey mike, I accidentally slept in too late this morning and missed the meeting, my apologies. Is there anyway we could meet today later in the day? Thanks

**Comment by mikeizbicki** [comment]
I'll be available tomorrow at about 1pm during my son's naptime if you want to
meet.  Otherwise, I won't be available until Wednesday.

**Comment by benfig1127** [comment]
Okay I will make sure I'm there at 1pm then. Thanks
