### ISSUE TITLE
Serious problem with my interface with the server

### ISSUE THREAD

**Issue by benfig1127** [benfig1127/Summer-Research-2020#16]
@mikeizbicki Hey Mike, in the 15 minutes after we finished talking something went seriously wrong with my account on the server. My entire UN_encoder file was corrupted and deleted from the server and anytime I try and write or edit any file it corrupts the file and returns the file size to 0 bytes. Furthermore I cannot install any packages due to the following error:
```
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/bfigueroa20']
```
Did something happen with my allocated disk space and it now overwrote my files?
Let me know if you have any thoughts.

**Comment by mikeizbicki** [comment]
I'm on zoom right now if you want me to look at it.

**Comment by benfig1127** [comment]
sounds good, im waiting in the lobby.
