### ISSUE TITLE
Problems with Creating a shared "mounted" folder to the lambda server

### ISSUE THREAD

**Issue by benfig1127** [benfig1127/Summer-Research-2020#6]
@mikeizbicki I was working through adding the BERT Model and made some significant progress writing out the code and wanted to try and run a test run after importing the python script and the data set onto the server. You mentioned that I can just create a local folder on my desktop that is synced with the server. I was having some trouble implementing this could you provide me some examples or help on how to do this on my ubuntu machine to your lambda server? Thanks

**Comment by mikeizbicki** [comment]
The command to use is `sshfs`.  I use it like
```
$ sshfs -p5055 ~/tmp/lambda-server mizbicki@134.173.191.241:/
```
but your invocation will be slightly different.

**Comment by benfig1127** [comment]
Awesome, and that command line (edited for my computer) will create a linked folder? For example, in your case it would link the folder at the CD "~/tmp/lambda-server"?
